# Site settings
title: David Zuidema
email: david@palaverist.com
description: "Musings of a Master Software Craftsman"
baseurl: ""
url: "https://www.palaverist.com/"
twitter_username: davidzuidema
github_username:  davidzuidema

# Build settings
markdown: kramdown
permalink: pretty
