# Site settings
title: Zubacca
email: david@zubacca.com
description: "Haskell and Web Development Stuff"
baseurl: ""
url: "http://zubacca.com"
twitter_username: davidzuidema
github_username:  davidzuidema

# Build settings
markdown: kramdown
permalink: pretty
